sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - 3.4.0
    
install:
  - haxelib install deep_equal
  - haxelib install tink_stringly
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix node
  - haxelib run travix python
  - haxelib run travix java

env:
  - secure: "wsfN3QARgC9Q6GV8IxCNVf1Ta26v+/1D6yJZHHvWeAqpR/nXSl6gpmKCH/LAe+B/ymN7EkqpcAMt4UdVlhISC1zqeSfIXBR3TlQnrIZYfR7TlLod3rDAZaS3WKTAP8XtXtFzTG3zmZ2gsGaGRsigY1ByFC1oaxduuJZkfUB4M9xZQdgsOkAZ8xj+J2RNFa2uHEh2PzoIpORN0Zh60sv1m9lPxoAh+K0O1opA+gg+x8pOQvqR+JdP8JFHVY4S8fvuV9mn/jJoUxiTugU64EHY6QiKTkGR3lxqfdv+q+9b1l12hBePtXYJfaYB9teNPqCt9HE7+mjwyWhxGN+86gIIw1SAkIqjERfaX45PInYDhIuYIwo379+tgB93cB7e7AIKygox5sAEgd2AZiogMFZfS07qaFOIR5gGDrTG/BFMYNwHWBYXvDrfvKPHmftGMREnqyJDTfcmRbVzOijc38egiWWfMAggBoIgPEsEFDwxOrtJwZV5TDtsZiXtdanwGnPRVLR8gFyR2177+zeYyuQ1Ok2YnzMz9IoMo/NaPjva3QAjtsTjzj/kpKrSjGbtDRCHMWEKywqNczKGszU6QpbVhGFm/yfPC1psAH1g+QZ7A3EPRysigo02pJX/nV1r/VwVc7JIivIka4Mp4s2AaFMMdZ0ECXzhe+K7ZtFjYa/2tRQ="

after_success:
- haxelib run travix release  